language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mands' ]; then cd .. && eval "mv $currentfolder generator-mands" && cd generator-mands; fi

